version: '3'
services:
  wiremock:
    container_name: wiremock
    image: rodolpheche/wiremock:2.30.1
    ports:
      - "9090:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
  localstack:
    image: localstack/localstack
    hostname: localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
    environment:
      - SKIP_SSL_CERT_DOWNLOAD=1
      - SERVICES=sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=ANUJDEKAVADIYAEXAMPLE
      - AWS_SECRET_ACCESS_KEY=2QvM4/Tdmf38SkcD/qalvXO4EXAMPLEKEY
      - SQS_ENDPOINT_STRATEGY=path
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"